
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module lab4(

	//////////// CLOCK //////////
	input 		          		ADC_CLK_10,
	input 		          		MAX10_CLK1_50,
	input 		          		MAX10_CLK2_50,

	//////////// SEG7 //////////
	output		     [7:0]		HEX0,
	output		     [7:0]		HEX1,
	output		     [7:0]		HEX2,
	output		     [7:0]		HEX3,
	output		     [7:0]		HEX4,
	output		     [7:0]		HEX5,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// SW //////////
	input 		     [9:0]		SW
);



    reg [9:0] shift_reg;
    
    assign LEDR[0] = shift_reg[0];
    assign LEDR[1] = shift_reg[1];
    assign LEDR[2] = shift_reg[2];
    assign LEDR[3] = shift_reg[3];
    assign LEDR[4] = shift_reg[4];
    assign LEDR[5] = shift_reg[5];
    assign LEDR[6] = shift_reg[6];
    assign LEDR[7] = shift_reg[7];
    assign LEDR[8] = shift_reg[8];
    assign LEDR[9] = shift_reg[9];
    
    always@(posedge KEY[0]) begin
        if(KEY[1]) begin
            shift_reg <= {SW[9],SW[8],SW[7],SW[6],SW[5],SW[4],SW[3],SW[2],SW[1],SW[0]};
        end
        else begin
            shift_reg <= {SW[9],shift_reg[9:1]};
        end
    end


endmodule
