//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module seg7(

	//////////// SEG7 //////////
	input				  [3:0]		bit4,
	output reg	 	  [7:0]		HEXOUT
	
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================

////////////USE A SINGLE CASE STATEMENT INSIDE AN ALWAYS BLOCK
///////OUT
always @(*)
begin
	case (bit4)
	4'b0000 : HEXOUT = 8'b11000000;
	4'b0001 : HEXOUT = 8'b11111001;
	4'b0010 : HEXOUT = 8'b10100100;
	4'b0011 : HEXOUT = 8'b10110000;
	4'b0100 : HEXOUT = 8'b10011001;
	4'b0101 : HEXOUT = 8'b10010010;
	4'b0110 : HEXOUT = 8'b10000010;
	4'b0111 : HEXOUT = 8'b11111000;
	4'b1000 : HEXOUT = 8'b10000000;
	4'b1001 : HEXOUT = 8'b10011000;
	4'b1010 : HEXOUT = 8'b10001000;
	4'b1011 : HEXOUT = 8'b10000011;
	4'b1100 : HEXOUT = 8'b11000110;
	4'b1101 : HEXOUT = 8'b10100001;
	4'b1110 : HEXOUT = 8'b10000110;
	4'b1111 : HEXOUT = 8'b10001110;
	endcase
end

endmodule
